engines:
  markdownlint:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "D"
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 60
ratings:
  paths:
  - "**.py"
  - "**.md"
exclude_paths:
- "LICENSE.md"
